#!/usr/bin/env python
import sys

try:
    from zabbixlib.cli import ZabbixCLI
except:
    raise Exception("ZabbixCLI tool require zabbixlib module be installed.")

# TODO: Flush database
# TODO: User management
# TODO: Check existence and remove unnecesery components (items, triggers etc.)

if __name__ == '__main__':
    ZabbixCLI()
